version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./database.db
    depends_on:
      - db
    command: poetry run uvicorn football.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: sqlite:latest
    volumes:
      - ./database.db:/data/database.db 